version: "3"
services:
  product-core-db:
    image: mongo
    container_name: product-core-db
    ports:
      - 57018:27017
    volumes:
      - $PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d
    networks:
      - application

  product-core:
    image: myRetail/product-core-web:latest
    environment:
      - MONGODB_HOST=product-core-db
      - MONGODB_PORT=27017
    networks:
      - application
    ports:
      - "8090:8090"

networks:
  application:
    driver: bridge
