version: "3"
services:
  product-core-db:
    image: mongo
    container_name: product-core-db
    ports:
      - 57018:27017
    volumes:
      - $PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d

  product-core:
    image: myretail/product-core:latest
    environment:
      - MONGODB_HOST=product-core-db
      - MONGODB_PORT=27017
    depends_on:
      - product-core-db
    ports:
      - "8090:8090"
